# permissions for end users to edit rocketchats.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rocketchat-editor-role
rules:
- apiGroups:
  - apps.libre.sh
  resources:
  - rocketchats
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.libre.sh
  resources:
  - rocketchats/status
  verbs:
  - get
