# permissions for end users to view rocketchats.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rocketchat-viewer-role
rules:
- apiGroups:
  - apps.libre.sh
  resources:
  - rocketchats
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.libre.sh
  resources:
  - rocketchats/status
  verbs:
  - get
